# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: myRayTracer 

# Builds project 'myRayTracer'...
.PHONY: myRayTracer
myRayTracer: 
	make --directory="myRayTracer/" --file=myRayTracer.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="myRayTracer/" --file=myRayTracer.makefile clean

